### Text Procssing 1
* Tokenization >> lemmatization or stemming >> Stopwords

1- tokenization is splitting text into words (word tokenization) or sentences


In [2]:
import nltk
from nltk.tokenize import word_tokenize

text = "The cats are running faster than the dogs in the park!"

In [3]:
tokens = word_tokenize(text.lower())

print("Tokens :", tokens)

Tokens : ['the', 'cats', 'are', 'running', 'faster', 'than', 'the', 'dogs', 'in', 'the', 'park', '!']


2- Stopwords is removing commun words like "the", "is", "and" and focusing on imprtant words

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

filtred_tokens = []

for word in tokens:
    if word.isalnum() and word not in stop_words:
        filtred_tokens.append(word)
print('txt after stopwords', filtred_tokens)

txt after stopwords ['cats', 'running', 'faster', 'dogs', 'park']


3- Lemmatization is reducing the words in thier base ex : running >> run

Use lemmatization when the understanding of the context and accurate reductions are more important. Use stemming when speed is more crucial and incorrect or non-dictionary words are acceptable.

In [8]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatized = [lemmatizer.lemmatize(word, pos='v') for word in filtred_tokens]

print('txt after lemmatazation', lemmatized)

txt after lemmatazation ['cat', 'run', 'faster', 'dog', 'park']


## Text Preprocessing 2 
 * BoW, TF-IDF, Unigrams, Bigrams

1 - Unigrams: Single words as features (e.g., "cat", "run")

In [10]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
documents = [
    "cat run fast park",
    "dog chase cat park",
    "cat dog play together"
]

In [ ]:
bow_vectorizer = CountVectorizer(ngram_range=(1,1))  
bow_matrix = bow_vectorizer.fit_transform(documents)

print("BoW Vocabulary:", bow_vectorizer.get_feature_names_out())
print("BoW matrix:\n", bow_matrix)

#  (numbre of doc, order of the word)

BoW Vocabulary: ['cat' 'chase' 'dog' 'fast' 'park' 'play' 'run' 'together']
BoW matrix:
   (0, 0)	1
  (0, 6)	1
  (0, 3)	1
  (0, 4)	1
  (1, 0)	1
  (1, 4)	1
  (1, 2)	1
  (1, 1)	1
  (2, 0)	1
  (2, 2)	1
  (2, 5)	1
  (2, 7)	1


2. Bigrams is Pairs of consecutive words (e.g., "black cat", "run fast")

In [ ]:
bigram_vectorizer = CountVectorizer(ngram_range=(2,2))

bow_matrix = bow_vectorizer.fit_transform(documents)

print("BoW Vocabulary:", bow_vectorizer.get_feature_names_out())
print("BoW Matrix:\n", bow_matrix.toarray())

# matrix of vocabulary as features, documents as row

BoW Vocabulary: ['cat' 'chase' 'dog' 'fast' 'park' 'play' 'run' 'together']
BoW Matrix:
 [[1 0 0 1 1 0 1 0]
 [1 1 1 0 1 0 0 0]
 [1 0 1 0 0 1 0 1]]


3- Bag of Words (BoW): Represents text as a vector

In [17]:
# Unigrams + Bigrams combined with BoW
unigram_bigram = CountVectorizer(ngram_range=(1,2))
print("\nUnigram+Bigram Vocab:", unigram_bigram.fit(documents).get_feature_names_out())


Unigram+Bigram Vocab: ['cat' 'cat dog' 'cat park' 'cat run' 'chase' 'chase cat' 'dog'
 'dog chase' 'dog play' 'fast' 'fast park' 'park' 'play' 'play together'
 'run' 'run fast' 'together']


4- TF-IDF:  improves BoW by giving higher weight to words
* Common words like "cat" (appears in all 3 docs) get low weight.
* Rare words like "fast" or "chase" (appear in only 1 doc) get high weight.

* TF = number of reputation of words in sentences / number of words in the sentence  ;  IDF = log10(N/n)  ;  N = total number of documents(sentences)  ;  n = ns containins the word

TF -IDF = TF * IDF

In [ ]:
tfidf_vectorizer = TfidfVectorizer(ngram_range=(1,2))
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("tfidf_vecabulary", tfidf_vectorizer.get_feature_names_out())
print("tfidf_matrix", tfidf_matrix.toarray())

# rare words now get +0.41 score

tfidf_vecabulary ['cat' 'cat dog' 'cat park' 'cat run' 'chase' 'chase cat' 'dog'
 'dog chase' 'dog play' 'fast' 'fast park' 'park' 'play' 'play together'
 'run' 'run fast' 'together']
tfidf_matrix [[0.2425937  0.         0.         0.41074684 0.         0.
  0.         0.         0.         0.41074684 0.41074684 0.31238356
  0.         0.         0.41074684 0.41074684 0.        ]
 [0.25171084 0.         0.4261835  0.         0.4261835  0.4261835
  0.32412354 0.4261835  0.         0.         0.         0.32412354
  0.         0.         0.         0.         0.        ]
 [0.2425937  0.41074684 0.         0.         0.         0.
  0.31238356 0.         0.41074684 0.         0.         0.
  0.41074684 0.41074684 0.         0.         0.41074684]]


* Major issue with past technics is
 - sementic meaning ex (good = better) 
 - sparser matrix (lot of zeros or decimal numbers in tf-idf) which lead to high dimentions

 which word2vec solve this issues by subtract similair words  

## Text Preprocessing 3 → Word2Vec, Avg Word2Vec

Word embeddings has two types :

* 1 count of frequency (BOW - TF-IDF - OHE)
* 2   DL Trained model (Word2vec (1- CBOW), (2- SkipGrams))
 - so we use embedding layer to convert text into vectors

suppose we have 2D vecotrs like  : man = [0.49, 0.98] , king = [0.75, 0.95], queen =[0.95, 0.74], woman = [-0.95, -0.88]

king - man + woman = queen

calculating this using cosine similarity (also we can use ecludian distance)

* Distance = 1 - cosine similarity(cos teta) wich is the angel between the two points ex 45o  =  1-0.71 = 0.29



expaining cbow + skipgram (for bi data)....
there is word2vec goolgle-news-300 pretrained model