In [1]:
import pandas as pd
import numpy as np

In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
 import tensorflow as tf
print(tf.__version__)

2.17.0


In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[338, 20, 139, 374], [338, 20, 139, 231], [338, 122, 139, 438], [253, 453, 416, 326, 459], [253, 453, 416, 326, 207], [2, 338, 469, 139, 179], [52, 467, 303, 326]]


In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  # this make vector same size by adding zeros in beginning or in last
from tensorflow.keras.models import Sequential

In [ ]:
## pre padding result
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 338  20 139 374]
 [  0   0   0   0 338  20 139 231]
 [  0   0   0   0 338 122 139 438]
 [  0   0   0 253 453 416 326 459]
 [  0   0   0 253 453 416 326 207]
 [  0   0   0   2 338 469 139 179]
 [  0   0   0   0  52 467 303 326]]


In [ ]:
## 10 feature dimesnions like word2vec and here each number likr (0) with 10 diffrent representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

C:\Users\yazid\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 338,  20, 139, 374])

In [15]:
import tensorflow as tf

# Ensure embedded_docs is a tf.Tensor
# The Embedding layer expects integer inputs, so we specify dtype=tf.int32
tf_embedded_docs = tf.convert_to_tensor(embedded_docs, dtype=tf.int32)
print(model.predict(tf_embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
[[[ 4.82095815e-02 -4.45336364e-02 -3.06350719e-02  4.23453934e-02
    3.15467604e-02 -6.82412460e-03  1.74093880e-02 -1.52426958e-03
    2.21028067e-02 -4.39956188e-02]
  [ 4.82095815e-02 -4.45336364e-02 -3.06350719e-02  4.23453934e-02
    3.15467604e-02 -6.82412460e-03  1.74093880e-02 -1.52426958e-03
    2.21028067e-02 -4.39956188e-02]
  [ 4.82095815e-02 -4.45336364e-02 -3.06350719e-02  4.23453934e-02
    3.15467604e-02 -6.82412460e-03  1.74093880e-02 -1.52426958e-03
    2.21028067e-02 -4.39956188e-02]
  [ 4.82095815e-02 -4.45336364e-02 -3.06350719e-02  4.23453934e-02
    3.15467604e-02 -6.82412460e-03  1.74093880e-02 -1.52426958e-03
    2.21028067e-02 -4.39956188e-02]
  [ 1.97087862e-02 -1.85547844e-02 -2.13608891e-03 -1.32129788e-02
    1.29777454e-02  6.65706396e-03  1.86862238e-02  4.09111045e-02
    4.10836972e-02 -4.20825966e-02]
  [-4.36733142e-02 -1.52032748e-02  2.03325786e-02 -5.74134663e-03
   -1.72133930e-02 -4.76014391e-02 -3.320822

In [16]:
embedded_docs[0]

array([  0,   0,   0,   0, 338,  20, 139, 374])

In [17]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[ 0.04820958 -0.04453364 -0.03063507  0.04234539  0.03154676 -0.00682412
   0.01740939 -0.00152427  0.02210281 -0.04399562]
 [ 0.04820958 -0.04453364 -0.03063507  0.04234539  0.03154676 -0.00682412
   0.01740939 -0.00152427  0.02210281 -0.04399562]
 [ 0.04820958 -0.04453364 -0.03063507  0.04234539  0.03154676 -0.00682412
   0.01740939 -0.00152427  0.02210281 -0.04399562]
 [ 0.04820958 -0.04453364 -0.03063507  0.04234539  0.03154676 -0.00682412
   0.01740939 -0.00152427  0.02210281 -0.04399562]
 [ 0.01970879 -0.01855478 -0.00213609 -0.01321298  0.01297775  0.00665706
   0.01868622  0.0409111   0.0410837  -0.0420826 ]
 [-0.04367331 -0.01520327  0.02033258 -0.00574135 -0.01721339 -0.04760144
  -0.03320823  0.0302745   0.02525634 -0.01177083]
 [ 0.04358549  0.02837192 -0.03665872  0.0482653  -0.00100354  0.00934738
   0.02835744  0.00978795  0.0460535   0.04179095]
 [ 0.03947515  0.01069641  0.03114766  0.01920009  0.04861077 -0.02724359
  -0.03514846

In [18]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]